import turtle
from turtle import *
window = turtle.Screen()
window.tracer(False)
hideturtle()
turtle.Screen().bgcolor("skyblue")
tom = Turtle()
tom.shape('turtle')

tom.penup()
tom.goto(-0, 100)
tom.pendown()
tom.color("orange")
tom.begin_fill()
tom.circle(100)
tom.end_fill()

tom.penup()
tom.goto(-0, 120)
tom.pendown()
tom.color("yellow")
tom.begin_fill()
tom.circle(100)
tom.end_fill()

tom.penup()
tom.goto(150, -150)
tom.pendown()
tom.color("green")
tom.width(5)
tom.setheading(90)
tom.fd(50)
tom.right(30)
tom.forward(30)
tom.penup()
tom.backward(30)
tom.pendown()
tom.left(60)
tom.forward(30)
tom.penup()
tom.backward(30)
tom.pendown()


tom.hideturtle()
window.tracer(True)
turtle.exitonclick()